### PR TITLE
Remove array reference from site id

### PR DESCRIPTION
**Pull request by genehallman**

### CODE REVIEW

**Comment by yawetse** [comment]
yeah this is a weird bug, not sure why, but when that command line argument is being parsed, it's sending both the value of the site id and "true"

is that not happening for you?

**Comment by genehallman** [comment]
Its not happening for me. What platform are you on? Could it be an issue with optimist?

On line 29, try adding:
console.log(typeof __SITE_ID);
And see what SITE_ID's type is. 
Mine is "number".

I'm running it with:

node app.js -t "Gene node test" -n "labs-t402.fyre.co" -s "303827" -k "my secret" -u "http://demos.livefyre.com/labs-t402" -c "gene_node_test_1"

**Comment by yawetse** [comment]
It may be an optimist issue, I'm on OSX 10.8

**Comment by genehallman** [comment]
Hmm... me too. Was your typeof __SITE_ID a number?

Are you running it with quotes around your arguments?

**Comment by yawetse** [comment]
I will double check a little later tonight but I don't believe I was running it with quotes around the siteID argument

I actually haven't been able to check what the type of the value is yet, but as soon as I do, I'll let you know what comes up.

Thanks for helping clean this up btw!

**Comment by genehallman** [comment]
Not a problem.
I've linked your work to our docs repo. Thanks for the contribution!

https://github.com/Livefyre/livefyre-docs/tree/master/misc/convCreator

As a syntax note, I've noticed you're missing a few line-ending semi-colons too. I didnt bother submitting a PR for that though, I figured you could run JSLint on it.

**Comment by yawetse** [comment]
Sorry about that! I cobbled this together extremely quickly, I should probably write some tests too

**Comment by genehallman** [comment]
No problem, we're always looking for open contributions to help other developers. Really appreciate the time you took to code this up and give us the twitter shout out - Thanks!

**Pull request merged**
